name: github_client
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  oauth2: ^2.0.0
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  webview_flutter: ^3.0.4
  flash: ^2.0.3+2
  auto_route: ^4.0.1
  flutter_secure_storage: ^5.0.2
  flutter_screenutil: ^5.5.3+1
  material_design_icons_flutter: ^5.0.6595
  google_fonts: ^3.0.1
  json_annotation: ^4.5.0
  sembast: ^3.2.0
  path_provider: ^2.0.10
  path: ^1.8.1
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  material_floating_search_bar: ^0.3.7

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lint: ^1.8.2
 


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
